default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  username: <%= ENV.fetch('APP_DATABASE_USER') %>
  password: <%= ENV.fetch('APP_DATABASE_PASSWORD') %>

development:
  <<: *default
  database: app_development
  host: db

test:
  <<: *default
  database: app_test
  host: db

production:
  <<: *default
  database: app_production