default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  username: root
  password: root

development:
  <<: *default
  database: app_development
  host: db

test:
  <<: *default
  database: app_test
  host: db

production:
  <<: *default
  database: app_production